DROP TABLE game_stats;
DROP TABLE player_stats;

CREATE TABLE IF NOT EXISTS game_stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    player_id INTEGER NOT NULL,
    start DATETIME NOT NULL,
    stop DATETIME DEFAULT NULL,
    round INTEGER DEFAULT NULL,
    CONSTRAINT FK_65741E2599E6F5DF FOREIGN KEY (player_id) REFERENCES player_stats (id) NOT DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX IDX_65741E2599E6F5DF ON game_stats (player_id);

CREATE TABLE IF NOT EXISTS player_stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    balance FLOAT DEFAULT NULL,
    winning FLOAT DEFAULT NULL,
    bet INTEGER DEFAULT NULL
);
